services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-prod}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DataBase:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - yellow-network
    depends_on:
      - DataBase
    restart: unless-stopped


  DataBase:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yellow-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: ${ADMINER_CONTAINER_NAME:-adminer}
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    depends_on:
      - DataBase
    networks:
      - yellow-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  yellow-network:
    driver: bridge