server:
  port: 8080
  servlet:
    context-path: /yellow-pages/api

spring:
  application:
    name: Yellow-Pages
  datasource:
    url: jdbc:postgresql://localhost:5432/yellow-db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger