server:
  port: 8080
  servlet:
    context-path: /yellow-pages/api

spring:
  application:
    name: Yellow-Pages
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger